services:
  mcp-server:
    build:
      context: .
      dockerfile: mcp.Dockerfile
    ports:
      - "9001:8000"  # Mapea 9001 (host) → 8000 (contenedor)
    networks:
      - mcp-network
    environment:
      - PORT=8000  # El puerto interno del MCP sigue siendo 8000
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always

  fastapi-server:
    build:
      context: .
      dockerfile: main.Dockerfile
    ports:
      - "9000:8001"  # Mapea 9000 (host) → 8001 (contenedor)
    networks:
      - mcp-network
    depends_on:
      - mcp-server
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    networks:
      - mcp-network
    restart: always