version: '3.8'

services:
  mcp-server:
    expose:
      - "8000"
    build:
      context: .
      dockerfile: mcp.Dockerfile
    networks:
      - mcp-network
    environment:
      - PORT=8000
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always

  fastapi-server:
    build:
      context: .
      dockerfile: main.Dockerfile
    ports:
      - "9000:8001"
    networks:
      - mcp-network
    depends_on:
      - mcp-server
      - redis
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:7
    networks:
      - mcp-network
    restart: always

networks:
  mcp-network:
    driver: bridge
